stages:
  - test
  - clean

include:
  - project: 'production-purple/ci'
    file: '/templates/python-tox.yml'

clean_resources:
  stage: clean
  script:
    - export KUBECONFIG=tests_env/kubeconfig-pikdev-unittest-admin.conf
    - kubectl delete namespace lamp-client
    - kubectl delete pv rbd-pv-cust-db
    - kubectl delete pv rbd-pv-cust-www
  tags:
    - shell
    - purple

