include:
  - project: 'production-purple/ci'
    file: '/templates/python-tox.yml'

stages:
  - clean
clean:
  stage: clean
  script:
    - export KUBECONFIG=tests_env/kubeconfig-pikdev-unittest-admin.conf
    - kubectl delete pv rbd-pv-cust-db
    - kubectl delete pv rbd-pv-cust-www
    - kubectl delete namespace lamp-client
  tags:
    - shell
    - ansible
    - purple

